openapi: 3.0.0
info:
  title: PasswordValidate
  version: '1.0'
  contact:
    name: Marcelo
    email: marcelogim@gmail.com
  description: Web API for validate password
tags:
  - name: passwordValidate
    description: Validate password API
    externalDocs:
      description: Find out more
      url: 'https://github.com/marcelogim/PasswordValidate.git'
servers:
  - url: 'http://localhost:3000'
paths:
  /passwordValidate:
    post:
      tags:
        - passwordValidate
      summary: Validar Password
      operationId: post-password-validate
      responses:
        '200':
          description: Reponse 200 with a password validated with a parameter booleam true or false.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IsValid'
              examples:
                Validate Response:
                  value:
                    isValid: false
        '400':
          description: Missing Required Information in field password
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  type:
                    type: string
                    minLength: 1
                  title:
                    type: string
                    minLength: 1
                  status:
                    type: number
                  traceId:
                    type: string
                    minLength: 1
                  errors:
                    type: object
                    properties:
                      Password:
                        type: array
                        items:
                          required:
                            - Password
                          properties: {}
                    required:
                      - Password
                required:
                  - type
                  - title
                  - status
                  - traceId
                  - errors
              examples:
                errorResponse:
                  value:
                    type: 'https://tools.ietf.org/html/rfc7231#section-6.5.1'
                    title: One or more validation errors occurred.
                    status: 400
                    traceId: '|ed4bcb59-44c6d35f1a8c0730.'
                    errors:
                      Password:
                        - The Password field is required.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Password'
            examples:
              Validate Request:
                value:
                  password: Admin@123
          application/xml:
            schema:
              type: object
              properties: {}
        description: Method POST for validate password with a password parameter.
      description: API Password Validate.
components:
  schemas:
    Password:
      title: Password
      type: object
      description: Object Password Validate
      x-examples:
        password: Admin@123
      properties:
        password:
          type: string
      required:
        - password
    IsValid:
      title: isValid
      type: object
      description: Object Password Validate
      x-examples:
        isValid: true
      properties:
        isValid:
          type: boolean
      required:
        - isValid
